# Generated by Django 5.0.6 on 2024-05-21 05:28

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(default='unpublished', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_field', models.IntegerField()),
                ('in_sync_int', models.IntegerField(help_text='Stays the same as int_field')),
            ],
        ),
        migrations.CreateModel(
            name='ProtectedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='mymodel',
            trigger=pgtrigger.compiler.Trigger(name='keep_in_sync', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.in_sync_int = NEW.int_field; RETURN NEW;', hash='86d3c937d92276be0b242ff8397ff858182960da', operation='UPDATE OR INSERT', pgid='pgtrigger_keep_in_sync_3c09a', table='test_trigger_mymodel', when='BEFORE')),
        ),
        migrations.AddField(
            model_name='protectedmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
