# Generated by Django 5.0.6 on 2024-05-21 05:31

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='mymodel',
            name='keep_in_sync',
        ),
    ]
