# Generated by Django 5.0.6 on 2024-05-21 05:36

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0002_remove_mymodel_keep_in_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStampModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('editable_value', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BookModel',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='protectedmodel',
            name='user',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='timestampmodel',
            trigger=pgtrigger.compiler.Trigger(name='read_only_created_at', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='d17668ccd775b8c6f57868ab262cb9ddb744f8e6', operation='UPDATE', pgid='pgtrigger_read_only_created_at_5b5f4', table='test_trigger_timestampmodel', when='BEFORE')),
        ),
        migrations.DeleteModel(
            name='ProtectedModel',
        ),
    ]
