# Generated by Django 4.2.11 on 2024-05-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0003_timestampmodel_delete_bookmodel_delete_mymodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestampmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
