# Generated by Django 4.2.11 on 2024-05-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0004_alter_timestampmodel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TimeStampModel',
        ),
    ]
