# Generated by Django 4.2.11 on 2024-05-21 06:01

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0007_redundantupdatemodel_delete_softdelete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='unpublished')),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='RedundantUpdateModel',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='post',
            trigger=pgtrigger.compiler.Trigger(name='freeze_published_model', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."status" = \'published\')', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='fee85a5e15bc77432cb549ef7325f0f1b3e70c6c', operation='UPDATE', pgid='pgtrigger_freeze_published_model_ab0f1', table='test_trigger_post', when='BEFORE')),
        ),
    ]
