# Generated by Django 4.2.11 on 2024-05-21 06:05

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0008_post_delete_redundantupdatemodel_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='post',
            name='freeze_published_model',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='post',
            trigger=pgtrigger.compiler.Trigger(name='freeze_publish_model_allowed_deactivate', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."status" = \'published\' AND NOT (NEW."status" = \'inactive\'))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='0604a654b066d136715366769a635868a8d7425a', operation='UPDATE', pgid='pgtrigger_freeze_publish_model_allowed_deactivate_c871b', table='test_trigger_post', when='BEFORE')),
        ),
    ]
