# Generated by Django 5.0.6 on 2024-05-21 06:35

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0012_historymodel_trackedmodel_trackedmodel_track_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_field', models.IntegerField()),
                ('char_field', models.CharField(null=True)),
                ('dt_field', models.DateTimeField(auto_now=True)),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='updatecheck',
            trigger=pgtrigger.compiler.Trigger(name='update_check', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (NOT (OLD.* IS DISTINCT FROM NEW.*))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='1fdaabb9e3c97c2a0f0b56fa6a3a2bb532d67fc8', operation='UPDATE', pgid='pgtrigger_update_check_5bb95', table='test_trigger_updatecheck', when='BEFORE')),
        ),
    ]
