# Generated by Django 5.0.6 on 2024-05-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0013_updatecheck_updatecheck_update_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatecheck',
            name='dt_field',
        ),
    ]
