# Generated by Django 5.0.6 on 2024-05-21 06:40

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0014_remove_updatecheck_dt_field'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='updatecheck',
            trigger=pgtrigger.compiler.Trigger(name='change_protect_update_check', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."char_field" IS DISTINCT FROM (NEW."char_field") OR OLD."int_field" IS DISTINCT FROM (NEW."int_field"))', func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;", hash='54d933b6794a11c32d11afe2e623feada73d0622', operation='UPDATE', pgid='pgtrigger_change_protect_update_check_b47b5', table='test_trigger_updatecheck', when='BEFORE')),
        ),
    ]
