# Generated by Django 5.0.6 on 2024-05-21 06:46

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0015_updatecheck_change_protect_update_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppendOnlyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', models.IntegerField()),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appendonlymodel',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='a0f391548f749e0ed540a309b641cecd17379775', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_0ff75', table='test_trigger_appendonlymodel', when='BEFORE')),
        ),
    ]
