# Generated by Django 5.0.6 on 2024-05-21 06:52

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0016_appendonlymodel_appendonlymodel_append_only'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='post',
            name='freeze_published_model',
        ),
    ]
