# Generated by Django 5.0.6 on 2024-05-21 07:33

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0018_remove_appendonlymodel_append_only'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='appendonlymodel',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='a0f391548f749e0ed540a309b641cecd17379775', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_0ff75', table='test_trigger_appendonlymodel', when='BEFORE')),
        ),
    ]
