# Generated by Django 5.0.6 on 2024-05-21 09:09

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0020_remove_appendonlymodel_append_only_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='appendonlymodel',
            name='append_only_with_calculation',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appendonlymodel',
            trigger=pgtrigger.compiler.Trigger(name='append_only_with_calculation', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            BEGIN\n                -- Perform a calculation or check\n                IF NEW.my_field < 0 THEN\n                    RAISE EXCEPTION 'my_field cannot be negative';\n                END IF;\n\n                -- Protect the row from updates or deletes\n                RAISE EXCEPTION 'Operation not allowed on this table';\n                RETURN NULL;\n            END;\n        ", hash='18a03e94f499c95e00b227c0ba12c1f3afbc510b', operation='INSERT', pgid='pgtrigger_append_only_with_calculation_ab17d', table='test_trigger_appendonlymodel', when='BEFORE')),
        ),
    ]
