# Generated by Django 5.0.6 on 2024-05-21 09:11

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0021_remove_appendonlymodel_append_only_with_calculation_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='appendonlymodel',
            name='append_only_with_calculation',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appendonlymodel',
            trigger=pgtrigger.compiler.Trigger(name='append_only_with_calculation', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            BEGIN\n                -- Protect the row from updates or deletes\n                RAISE EXCEPTION 'Operation not allowed on this table';\n                RETURN NULL;\n            END;\n        ", hash='4a6aed25fb6781154a59c3ba7ade61851af2cb5f', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_with_calculation_ab17d', table='test_trigger_appendonlymodel', when='BEFORE')),
        ),
    ]
