# Generated by Django 5.0.6 on 2024-05-21 09:30

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0023_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='transaction',
            trigger=pgtrigger.compiler.Trigger(name='prevent_update_delete_on_processed_transactions', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            BEGIN \n                --Check if the transaction has been processed\n                IF OLD.processed THEN\n                    RAISE EXCEPTION 'Cannot update or delete a processed transaction';\n                END IF;\n                \n                -- Check if the amount is positive\n                IF NEW.amount <= 0 THEN\n                    RAISE EXCEPTION 'Transaction amount must be positive';\n                END IF;\n                RETURN NULL;\n            END;\n        ", hash='dc5f24fb6cd20c689ffa16c77f7531ce4539e581', operation='UPDATE OR DELETE', pgid='pgtrigger_prevent_update_delete_on_processed_transactions_a6536', table='test_trigger_transaction', when='BEFORE')),
        ),
    ]
