# Generated by Django 5.0.6 on 2024-05-21 09:35

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0025_remove_transaction_prevent_update_delete_on_processed_transactions_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='transaction',
            name='prevent_update_delete_on_processed_transactions',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='transaction',
            trigger=pgtrigger.compiler.Trigger(name='prevent_update_delete_on_processed_transactions', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n            BEGIN\n                -- Skip validation if processed and amount are not being changed\n                IF NOT (OLD.processed IS DISTINCT FROM NEW.processed OR OLD.amount IS DISTINCT FROM NEW.amount) THEN\n                    RETURN NULL;\n                END IF;\n\n                -- Check if the transaction has been processed\n                IF OLD.processed THEN\n                    RAISE EXCEPTION 'Cannot update or delete a processed transaction';\n                END IF;\n\n                -- Check if the amount is positive\n                IF NEW.amount <= 0 THEN\n                    RAISE EXCEPTION 'Transaction amount must be positive';\n                END IF;\n\n                -- Exclude primary key updates\n                IF OLD.id IS DISTINCT FROM NEW.id THEN\n                    RETURN NULL;\n                END IF;\n\n                RETURN NULL;\n            END;\n        ", hash='1613c06cd6f113b2f18438c015729cfefad49fd2', operation='UPDATE OR DELETE', pgid='pgtrigger_prevent_update_delete_on_processed_transactions_a6536', table='test_trigger_transaction', when='BEFORE')),
        ),
    ]
