# Generated by Django 5.0.6 on 2024-05-21 10:09

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_trigger', '0027_remove_transaction_prevent_update_delete_on_processed_transactions_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='transaction',
            name='prevent_update_delete_on_processed_transactions',
        ),
    ]
